#ifndef WASM_H_GENERATED_
#define WASM_H_GENERATED_
/* Automically generated by wasm2c */
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

#include "wasm-rt.h"

#ifndef WASM_RT_MODULE_PREFIX
#define WASM_RT_MODULE_PREFIX
#endif

#define WASM_RT_PASTE_(x, y) x ## y
#define WASM_RT_PASTE(x, y) WASM_RT_PASTE_(x, y)
#define WASM_RT_ADD_PREFIX(x) WASM_RT_PASTE(WASM_RT_MODULE_PREFIX, x)

/* TODO(binji): only use stdint.h types in header */
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;

extern void WASM_RT_ADD_PREFIX(init)(void);

/* import: 'js' 'drawThwomp' */
extern void (*Z_jsZ_drawThwompZ_vifii)(u32, f32, u32, u32);
/* import: 'js' 'setFill' */
extern void (*Z_jsZ_setFillZ_viii)(u32, u32, u32);
/* import: 'js' 'contextFillRect' */
extern void (*Z_jsZ_contextFillRectZ_viiif)(u32, u32, u32, f32);
/* import: 'js' 'contextFillRect' */
extern void (*Z_jsZ_contextFillRectZ_vifii)(u32, f32, u32, u32);
/* import: 'js' 'contextFillRect' */
extern void (*Z_jsZ_contextFillRectZ_vifif)(u32, f32, u32, f32);
/* import: 'js' 'nextFrame' */
extern void (*Z_jsZ_nextFrameZ_vv)(void);
/* import: 'js' 'contextClearRect' */
extern void (*Z_jsZ_contextClearRectZ_viiii)(u32, u32, u32, u32);
/* import: 'js' 'Math.random' */
extern f32 (*Z_jsZ_MathZ2ErandomZ_fv)(void);

/* export: 'draw' */
extern void (*WASM_RT_ADD_PREFIX(Z_drawZ_vv))(void);
/* export: 'update' */
extern void (*WASM_RT_ADD_PREFIX(Z_updateZ_vv))(void);
/* export: 'flap' */
extern void (*WASM_RT_ADD_PREFIX(Z_flapZ_vv))(void);
/* export: 'loop' */
extern void (*WASM_RT_ADD_PREFIX(Z_loopZ_vv))(void);
/* export: 'test' */
extern void (*WASM_RT_ADD_PREFIX(Z_testZ_vv))(void);
/* export: 'memory' */
extern wasm_rt_memory_t (*WASM_RT_ADD_PREFIX(Z_memory));
#ifdef __cplusplus
}
#endif

#endif  /* WASM_H_GENERATED_ */
/* Automically generated by wasm2c */
#include <math.h>
#include <string.h>

#include "wasm.h"
#define UNLIKELY(x) __builtin_expect(!!(x), 0)
#define LIKELY(x) __builtin_expect(!!(x), 1)

#define TRAP(x) (wasm_rt_trap(WASM_RT_TRAP_##x), 0)

#define FUNC_PROLOGUE                                            \
  if (++wasm_rt_call_stack_depth > WASM_RT_MAX_CALL_STACK_DEPTH) \
    TRAP(EXHAUSTION)

#define FUNC_EPILOGUE --wasm_rt_call_stack_depth

#define UNREACHABLE TRAP(UNREACHABLE)

#define CALL_INDIRECT(table, t, ft, x, ...)          \
  (LIKELY((x) < table.size && table.data[x].func &&  \
          table.data[x].func_type == func_types[ft]) \
       ? ((t)table.data[x].func)(__VA_ARGS__)        \
       : TRAP(CALL_INDIRECT))

#if WASM_RT_MEMCHECK_SIGNAL_HANDLER
#define MEMCHECK(mem, a, t)
#else
#define MEMCHECK(mem, a, t)  \
  if (UNLIKELY((a) + sizeof(t) > mem->size)) TRAP(OOB)
#endif

#if WABT_BIG_ENDIAN
static inline void load_data(void *dest, const void *src, size_t n) {
  size_t i = 0;
  u8 *dest_chars = dest;
  memcpy(dest, src, n);
  for (i = 0; i < (n>>1); i++) {
    u8 cursor = dest_chars[i];
    dest_chars[i] = dest_chars[n - i - 1];
    dest_chars[n - i - 1] = cursor;
  }
}
#define LOAD_DATA(m, o, i, s) load_data(&(m.data[m.size - o - s]), i, s)
#define DEFINE_LOAD(name, t1, t2, t3)                                                 \
  static inline t3 name(wasm_rt_memory_t* mem, u64 addr) {                            \
    MEMCHECK(mem, addr, t1);                                                          \
    t1 result;                                                                        \
    __builtin_memcpy(&result, &mem->data[mem->size - addr - sizeof(t1)], sizeof(t1)); \
    return (t3)(t2)result;                                                            \
  }

#define DEFINE_STORE(name, t1, t2)                                                     \
  static inline void name(wasm_rt_memory_t* mem, u64 addr, t2 value) {                 \
    MEMCHECK(mem, addr, t1);                                                           \
    t1 wrapped = (t1)value;                                                            \
    __builtin_memcpy(&mem->data[mem->size - addr - sizeof(t1)], &wrapped, sizeof(t1)); \
  }
#else
static inline void load_data(void *dest, const void *src, size_t n) {
  memcpy(dest, src, n);
}
#define LOAD_DATA(m, o, i, s) load_data(&(m.data[o]), i, s)
#define DEFINE_LOAD(name, t1, t2, t3)                        \
  static inline t3 name(wasm_rt_memory_t* mem, u64 addr) {   \
    MEMCHECK(mem, addr, t1);                                 \
    t1 result;                                               \
    __builtin_memcpy(&result, &mem->data[addr], sizeof(t1)); \
    return (t3)(t2)result;                                   \
  }

#define DEFINE_STORE(name, t1, t2)                                     \
  static inline void name(wasm_rt_memory_t* mem, u64 addr, t2 value) { \
    MEMCHECK(mem, addr, t1);                                           \
    t1 wrapped = (t1)value;                                            \
    __builtin_memcpy(&mem->data[addr], &wrapped, sizeof(t1));          \
  }
#endif

DEFINE_LOAD(i32_load, u32, u32, u32);
DEFINE_LOAD(i64_load, u64, u64, u64);
DEFINE_LOAD(f32_load, f32, f32, f32);
DEFINE_LOAD(f64_load, f64, f64, f64);
DEFINE_LOAD(i32_load8_s, s8, s32, u32);
DEFINE_LOAD(i64_load8_s, s8, s64, u64);
DEFINE_LOAD(i32_load8_u, u8, u32, u32);
DEFINE_LOAD(i64_load8_u, u8, u64, u64);
DEFINE_LOAD(i32_load16_s, s16, s32, u32);
DEFINE_LOAD(i64_load16_s, s16, s64, u64);
DEFINE_LOAD(i32_load16_u, u16, u32, u32);
DEFINE_LOAD(i64_load16_u, u16, u64, u64);
DEFINE_LOAD(i64_load32_s, s32, s64, u64);
DEFINE_LOAD(i64_load32_u, u32, u64, u64);
DEFINE_STORE(i32_store, u32, u32);
DEFINE_STORE(i64_store, u64, u64);
DEFINE_STORE(f32_store, f32, f32);
DEFINE_STORE(f64_store, f64, f64);
DEFINE_STORE(i32_store8, u8, u32);
DEFINE_STORE(i32_store16, u16, u32);
DEFINE_STORE(i64_store8, u8, u64);
DEFINE_STORE(i64_store16, u16, u64);
DEFINE_STORE(i64_store32, u32, u64);

#define I32_CLZ(x) ((x) ? __builtin_clz(x) : 32)
#define I64_CLZ(x) ((x) ? __builtin_clzll(x) : 64)
#define I32_CTZ(x) ((x) ? __builtin_ctz(x) : 32)
#define I64_CTZ(x) ((x) ? __builtin_ctzll(x) : 64)
#define I32_POPCNT(x) (__builtin_popcount(x))
#define I64_POPCNT(x) (__builtin_popcountll(x))

#define DIV_S(ut, min, x, y)                                 \
   ((UNLIKELY((y) == 0)) ?                TRAP(DIV_BY_ZERO)  \
  : (UNLIKELY((x) == min && (y) == -1)) ? TRAP(INT_OVERFLOW) \
  : (ut)((x) / (y)))

#define REM_S(ut, min, x, y)                                \
   ((UNLIKELY((y) == 0)) ?                TRAP(DIV_BY_ZERO) \
  : (UNLIKELY((x) == min && (y) == -1)) ? 0                 \
  : (ut)((x) % (y)))

#define I32_DIV_S(x, y) DIV_S(u32, INT32_MIN, (s32)x, (s32)y)
#define I64_DIV_S(x, y) DIV_S(u64, INT64_MIN, (s64)x, (s64)y)
#define I32_REM_S(x, y) REM_S(u32, INT32_MIN, (s32)x, (s32)y)
#define I64_REM_S(x, y) REM_S(u64, INT64_MIN, (s64)x, (s64)y)

#define DIVREM_U(op, x, y) \
  ((UNLIKELY((y) == 0)) ? TRAP(DIV_BY_ZERO) : ((x) op (y)))

#define DIV_U(x, y) DIVREM_U(/, x, y)
#define REM_U(x, y) DIVREM_U(%, x, y)

#define ROTL(x, y, mask) \
  (((x) << ((y) & (mask))) | ((x) >> (((mask) - (y) + 1) & (mask))))
#define ROTR(x, y, mask) \
  (((x) >> ((y) & (mask))) | ((x) << (((mask) - (y) + 1) & (mask))))

#define I32_ROTL(x, y) ROTL(x, y, 31)
#define I64_ROTL(x, y) ROTL(x, y, 63)
#define I32_ROTR(x, y) ROTR(x, y, 31)
#define I64_ROTR(x, y) ROTR(x, y, 63)

#define FMIN(x, y)                                          \
   ((UNLIKELY((x) != (x))) ? NAN                            \
  : (UNLIKELY((y) != (y))) ? NAN                            \
  : (UNLIKELY((x) == 0 && (y) == 0)) ? (signbit(x) ? x : y) \
  : (x < y) ? x : y)

#define FMAX(x, y)                                          \
   ((UNLIKELY((x) != (x))) ? NAN                            \
  : (UNLIKELY((y) != (y))) ? NAN                            \
  : (UNLIKELY((x) == 0 && (y) == 0)) ? (signbit(x) ? y : x) \
  : (x > y) ? x : y)

#define TRUNC_S(ut, st, ft, min, minop, max, x)                             \
  ((UNLIKELY((x) != (x)))                        ? TRAP(INVALID_CONVERSION) \
   : (UNLIKELY(!((x)minop(min) && (x) < (max)))) ? TRAP(INT_OVERFLOW)       \
                                                 : (ut)(st)(x))

#define I32_TRUNC_S_F32(x) TRUNC_S(u32, s32, f32, (f32)INT32_MIN, >=, 2147483648.f, x)
#define I64_TRUNC_S_F32(x) TRUNC_S(u64, s64, f32, (f32)INT64_MIN, >=, (f32)INT64_MAX, x)
#define I32_TRUNC_S_F64(x) TRUNC_S(u32, s32, f64, -2147483649., >, 2147483648., x)
#define I64_TRUNC_S_F64(x) TRUNC_S(u64, s64, f64, (f64)INT64_MIN, >=, (f64)INT64_MAX, x)

#define TRUNC_U(ut, ft, max, x)                                            \
  ((UNLIKELY((x) != (x)))                       ? TRAP(INVALID_CONVERSION) \
   : (UNLIKELY(!((x) > (ft)-1 && (x) < (max)))) ? TRAP(INT_OVERFLOW)       \
                                                : (ut)(x))

#define I32_TRUNC_U_F32(x) TRUNC_U(u32, f32, 4294967296.f, x)
#define I64_TRUNC_U_F32(x) TRUNC_U(u64, f32, (f32)UINT64_MAX, x)
#define I32_TRUNC_U_F64(x) TRUNC_U(u32, f64, 4294967296.,  x)
#define I64_TRUNC_U_F64(x) TRUNC_U(u64, f64, (f64)UINT64_MAX, x)

#define DEFINE_REINTERPRET(name, t1, t2)  \
  static inline t2 name(t1 x) {           \
    t2 result;                            \
    memcpy(&result, &x, sizeof(result));  \
    return result;                        \
  }

DEFINE_REINTERPRET(f32_reinterpret_i32, u32, f32)
DEFINE_REINTERPRET(i32_reinterpret_f32, f32, u32)
DEFINE_REINTERPRET(f64_reinterpret_i64, u64, f64)
DEFINE_REINTERPRET(i64_reinterpret_f64, f64, u64)


static u32 func_types[7];

static void init_func_types(void) {
  func_types[0] = wasm_rt_register_func_type(4, 0, WASM_RT_I32, WASM_RT_F32, WASM_RT_I32, WASM_RT_I32);
  func_types[1] = wasm_rt_register_func_type(3, 0, WASM_RT_I32, WASM_RT_I32, WASM_RT_I32);
  func_types[2] = wasm_rt_register_func_type(4, 0, WASM_RT_I32, WASM_RT_I32, WASM_RT_I32, WASM_RT_F32);
  func_types[3] = wasm_rt_register_func_type(4, 0, WASM_RT_I32, WASM_RT_F32, WASM_RT_I32, WASM_RT_F32);
  func_types[4] = wasm_rt_register_func_type(0, 0);
  func_types[5] = wasm_rt_register_func_type(4, 0, WASM_RT_I32, WASM_RT_I32, WASM_RT_I32, WASM_RT_I32);
  func_types[6] = wasm_rt_register_func_type(0, 1, WASM_RT_F32);
}

static void w2c_draw(void);
static void w2c_update(void);
static void w2c_flap(void);
static void w2c_loop(void);
static void w2c_test(void);

static void init_globals(void) {
}

static wasm_rt_memory_t w2c_memory;

static void w2c_draw(void) {
  u32 w2c_l0 = 0, w2c_l1 = 0, w2c_l2 = 0, w2c_l3 = 0, w2c_l4 = 0, w2c_l5 = 0;
  FUNC_PROLOGUE;
  u32 w2c_i0, w2c_i1, w2c_i2, w2c_i3, w2c_i4;
  f32 w2c_f0, w2c_f1, w2c_f2, w2c_f3, w2c_f4;
  w2c_i0 = 16u;
  w2c_i0 = i32_load((&w2c_memory), (u64)(w2c_i0));
  w2c_i1 = 4294967196u;
  w2c_i0 = (u32)((s32)w2c_i0 > (s32)w2c_i1);
  w2c_l0 = w2c_i0;
  w2c_i0 = 20u;
  w2c_f0 = f32_load((&w2c_memory), (u64)(w2c_i0));
  w2c_f1 = 0;
  w2c_i0 = w2c_f0 != w2c_f1;
  w2c_l1 = w2c_i0;
  w2c_i0 = w2c_l0;
  if (w2c_i0) {
    w2c_i0 = w2c_l1;
    w2c_l2 = w2c_i0;
  } else {
    w2c_i0 = 0u;
    w2c_l2 = w2c_i0;
  }
  w2c_i0 = w2c_l2;
  if (w2c_i0) {
    w2c_i0 = 8u;
    w2c_i0 = i32_load((&w2c_memory), (u64)(w2c_i0));
    w2c_i1 = 4294967196u;
    w2c_i0 = (u32)((s32)w2c_i0 > (s32)w2c_i1);
    w2c_l3 = w2c_i0;
    w2c_i0 = 12u;
    w2c_f0 = f32_load((&w2c_memory), (u64)(w2c_i0));
    w2c_f1 = 0;
    w2c_i0 = w2c_f0 != w2c_f1;
    w2c_l4 = w2c_i0;
    w2c_i0 = w2c_l3;
    if (w2c_i0) {
      w2c_i0 = w2c_l4;
      w2c_l5 = w2c_i0;
    } else {
      w2c_i0 = 0u;
      w2c_l5 = w2c_i0;
    }
    w2c_i0 = w2c_l5;
    if (w2c_i0) {
      w2c_i0 = 50u;
      w2c_i1 = 0u;
      w2c_f1 = f32_load((&w2c_memory), (u64)(w2c_i1));
      w2c_i2 = 40u;
      w2c_i3 = 45u;
      (*Z_jsZ_drawThwompZ_vifii)(w2c_i0, w2c_f1, w2c_i2, w2c_i3);
      w2c_i0 = 85u;
      w2c_i1 = 255u;
      w2c_i2 = 85u;
      (*Z_jsZ_setFillZ_viii)(w2c_i0, w2c_i1, w2c_i2);
      w2c_i0 = 8u;
      w2c_i0 = i32_load((&w2c_memory), (u64)(w2c_i0));
      w2c_i1 = 10u;
      w2c_i0 += w2c_i1;
      w2c_i1 = 0u;
      w2c_i2 = 80u;
      w2c_i3 = 12u;
      w2c_f3 = f32_load((&w2c_memory), (u64)(w2c_i3));
      w2c_f4 = 50;
      w2c_f3 -= w2c_f4;
      (*Z_jsZ_contextFillRectZ_viiif)(w2c_i0, w2c_i1, w2c_i2, w2c_f3);
      w2c_i0 = 17u;
      w2c_i1 = 255u;
      w2c_i2 = 17u;
      (*Z_jsZ_setFillZ_viii)(w2c_i0, w2c_i1, w2c_i2);
      w2c_i0 = 8u;
      w2c_i0 = i32_load((&w2c_memory), (u64)(w2c_i0));
      w2c_i1 = 12u;
      w2c_f1 = f32_load((&w2c_memory), (u64)(w2c_i1));
      w2c_f2 = 50;
      w2c_f1 -= w2c_f2;
      w2c_i2 = 100u;
      w2c_i3 = 50u;
      (*Z_jsZ_contextFillRectZ_vifii)(w2c_i0, w2c_f1, w2c_i2, w2c_i3);
      w2c_i0 = 17u;
      w2c_i1 = 255u;
      w2c_i2 = 17u;
      (*Z_jsZ_setFillZ_viii)(w2c_i0, w2c_i1, w2c_i2);
      w2c_i0 = 8u;
      w2c_i0 = i32_load((&w2c_memory), (u64)(w2c_i0));
      w2c_i1 = 12u;
      w2c_f1 = f32_load((&w2c_memory), (u64)(w2c_i1));
      w2c_f2 = 150;
      w2c_f1 += w2c_f2;
      w2c_i2 = 100u;
      w2c_i3 = 50u;
      (*Z_jsZ_contextFillRectZ_vifii)(w2c_i0, w2c_f1, w2c_i2, w2c_i3);
      w2c_i0 = 85u;
      w2c_i1 = 255u;
      w2c_i2 = 85u;
      (*Z_jsZ_setFillZ_viii)(w2c_i0, w2c_i1, w2c_i2);
      w2c_i0 = 8u;
      w2c_i0 = i32_load((&w2c_memory), (u64)(w2c_i0));
      w2c_i1 = 10u;
      w2c_i0 += w2c_i1;
      w2c_i1 = 12u;
      w2c_f1 = f32_load((&w2c_memory), (u64)(w2c_i1));
      w2c_f2 = 200;
      w2c_f1 += w2c_f2;
      w2c_i2 = 80u;
      w2c_f3 = 500;
      w2c_i4 = 12u;
      w2c_f4 = f32_load((&w2c_memory), (u64)(w2c_i4));
      w2c_f3 -= w2c_f4;
      (*Z_jsZ_contextFillRectZ_vifif)(w2c_i0, w2c_f1, w2c_i2, w2c_f3);
    }
    w2c_i0 = 85u;
    w2c_i1 = 255u;
    w2c_i2 = 85u;
    (*Z_jsZ_setFillZ_viii)(w2c_i0, w2c_i1, w2c_i2);
    w2c_i0 = 16u;
    w2c_i0 = i32_load((&w2c_memory), (u64)(w2c_i0));
    w2c_i1 = 10u;
    w2c_i0 += w2c_i1;
    w2c_i1 = 0u;
    w2c_i2 = 80u;
    w2c_i3 = 20u;
    w2c_f3 = f32_load((&w2c_memory), (u64)(w2c_i3));
    w2c_f4 = 50;
    w2c_f3 -= w2c_f4;
    (*Z_jsZ_contextFillRectZ_viiif)(w2c_i0, w2c_i1, w2c_i2, w2c_f3);
    w2c_i0 = 17u;
    w2c_i1 = 255u;
    w2c_i2 = 17u;
    (*Z_jsZ_setFillZ_viii)(w2c_i0, w2c_i1, w2c_i2);
    w2c_i0 = 16u;
    w2c_i0 = i32_load((&w2c_memory), (u64)(w2c_i0));
    w2c_i1 = 20u;
    w2c_f1 = f32_load((&w2c_memory), (u64)(w2c_i1));
    w2c_f2 = 50;
    w2c_f1 -= w2c_f2;
    w2c_i2 = 100u;
    w2c_i3 = 50u;
    (*Z_jsZ_contextFillRectZ_vifii)(w2c_i0, w2c_f1, w2c_i2, w2c_i3);
    w2c_i0 = 17u;
    w2c_i1 = 255u;
    w2c_i2 = 17u;
    (*Z_jsZ_setFillZ_viii)(w2c_i0, w2c_i1, w2c_i2);
    w2c_i0 = 16u;
    w2c_i0 = i32_load((&w2c_memory), (u64)(w2c_i0));
    w2c_i1 = 20u;
    w2c_f1 = f32_load((&w2c_memory), (u64)(w2c_i1));
    w2c_f2 = 150;
    w2c_f1 += w2c_f2;
    w2c_i2 = 100u;
    w2c_i3 = 50u;
    (*Z_jsZ_contextFillRectZ_vifii)(w2c_i0, w2c_f1, w2c_i2, w2c_i3);
    w2c_i0 = 85u;
    w2c_i1 = 255u;
    w2c_i2 = 85u;
    (*Z_jsZ_setFillZ_viii)(w2c_i0, w2c_i1, w2c_i2);
    w2c_i0 = 16u;
    w2c_i0 = i32_load((&w2c_memory), (u64)(w2c_i0));
    w2c_i1 = 10u;
    w2c_i0 += w2c_i1;
    w2c_i1 = 20u;
    w2c_f1 = f32_load((&w2c_memory), (u64)(w2c_i1));
    w2c_f2 = 200;
    w2c_f1 += w2c_f2;
    w2c_i2 = 80u;
    w2c_f3 = 500;
    w2c_i4 = 20u;
    w2c_f4 = f32_load((&w2c_memory), (u64)(w2c_i4));
    w2c_f3 -= w2c_f4;
    (*Z_jsZ_contextFillRectZ_vifif)(w2c_i0, w2c_f1, w2c_i2, w2c_f3);
  }
  FUNC_EPILOGUE;
}

static void w2c_update(void) {
  u32 w2c_l0 = 0, w2c_l1 = 0, w2c_l2 = 0, w2c_l3 = 0, w2c_l5 = 0, w2c_l6 = 0, w2c_l7 = 0, w2c_l8 = 0;
  f32 w2c_l4 = 0, w2c_l9 = 0;
  FUNC_PROLOGUE;
  u32 w2c_i0, w2c_i1, w2c_i2, w2c_i3;
  f32 w2c_f1, w2c_f2;
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_f1 = f32_load((&w2c_memory), (u64)(w2c_i1));
  w2c_i2 = 4u;
  w2c_f2 = f32_load((&w2c_memory), (u64)(w2c_i2));
  w2c_f1 += w2c_f2;
  f32_store((&w2c_memory), (u64)(w2c_i0), w2c_f1);
  w2c_i0 = 4u;
  w2c_i1 = 4u;
  w2c_f1 = f32_load((&w2c_memory), (u64)(w2c_i1));
  w2c_f2 = 0.5;
  w2c_f1 += w2c_f2;
  f32_store((&w2c_memory), (u64)(w2c_i0), w2c_f1);
  w2c_i0 = 8u;
  w2c_i1 = 8u;
  w2c_i1 = i32_load((&w2c_memory), (u64)(w2c_i1));
  w2c_i2 = 4294967196u;
  w2c_i1 = (u32)((s32)w2c_i1 < (s32)w2c_i2);
  w2c_l0 = w2c_i1;
  w2c_i1 = 12u;
  w2c_f1 = f32_load((&w2c_memory), (u64)(w2c_i1));
  w2c_f2 = 0;
  w2c_i1 = w2c_f1 == w2c_f2;
  w2c_l1 = w2c_i1;
  w2c_i1 = w2c_l0;
  if (w2c_i1) {
    w2c_i1 = w2c_l0;
    w2c_l2 = w2c_i1;
  } else {
    w2c_i1 = w2c_l1;
    if (w2c_i1) {
      w2c_i1 = w2c_l1;
      w2c_l2 = w2c_i1;
    } else {
      w2c_i1 = 0u;
      w2c_l2 = w2c_i1;
    }
  }
  w2c_i1 = w2c_l2;
  if (w2c_i1) {
    w2c_f1 = 0;
    w2c_i2 = 8u;
    w2c_i2 = i32_load((&w2c_memory), (u64)(w2c_i2));
    w2c_l3 = w2c_i2;
    w2c_l4 = w2c_f1;
  } else {
    w2c_i1 = 12u;
    w2c_f1 = f32_load((&w2c_memory), (u64)(w2c_i1));
    w2c_i2 = 8u;
    w2c_i2 = i32_load((&w2c_memory), (u64)(w2c_i2));
    w2c_i3 = 1u;
    w2c_i2 -= w2c_i3;
    w2c_l3 = w2c_i2;
    w2c_l4 = w2c_f1;
  }
  w2c_i1 = w2c_l3;
  i32_store((&w2c_memory), (u64)(w2c_i0), w2c_i1);
  w2c_i0 = 12u;
  w2c_f1 = w2c_l4;
  f32_store((&w2c_memory), (u64)(w2c_i0), w2c_f1);
  w2c_i0 = 16u;
  w2c_i1 = 16u;
  w2c_i1 = i32_load((&w2c_memory), (u64)(w2c_i1));
  w2c_i2 = 4294967196u;
  w2c_i1 = (u32)((s32)w2c_i1 < (s32)w2c_i2);
  w2c_l5 = w2c_i1;
  w2c_i1 = 20u;
  w2c_f1 = f32_load((&w2c_memory), (u64)(w2c_i1));
  w2c_f2 = 0;
  w2c_i1 = w2c_f1 == w2c_f2;
  w2c_l6 = w2c_i1;
  w2c_i1 = w2c_l5;
  if (w2c_i1) {
    w2c_i1 = w2c_l5;
    w2c_l7 = w2c_i1;
  } else {
    w2c_i1 = w2c_l6;
    if (w2c_i1) {
      w2c_i1 = w2c_l6;
      w2c_l7 = w2c_i1;
    } else {
      w2c_i1 = 0u;
      w2c_l7 = w2c_i1;
    }
  }
  w2c_i1 = w2c_l7;
  if (w2c_i1) {
    w2c_f1 = 0;
    w2c_i2 = 16u;
    w2c_i2 = i32_load((&w2c_memory), (u64)(w2c_i2));
    w2c_l8 = w2c_i2;
    w2c_l9 = w2c_f1;
  } else {
    w2c_i1 = 20u;
    w2c_f1 = f32_load((&w2c_memory), (u64)(w2c_i1));
    w2c_i2 = 16u;
    w2c_i2 = i32_load((&w2c_memory), (u64)(w2c_i2));
    w2c_i3 = 1u;
    w2c_i2 -= w2c_i3;
    w2c_l8 = w2c_i2;
    w2c_l9 = w2c_f1;
  }
  w2c_i1 = w2c_l8;
  i32_store((&w2c_memory), (u64)(w2c_i0), w2c_i1);
  w2c_i0 = 20u;
  w2c_f1 = w2c_l9;
  f32_store((&w2c_memory), (u64)(w2c_i0), w2c_f1);
  FUNC_EPILOGUE;
}

static void w2c_flap(void) {
  FUNC_PROLOGUE;
  u32 w2c_i0, w2c_i1;
  f32 w2c_f1;
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_f1 = f32_load((&w2c_memory), (u64)(w2c_i1));
  f32_store((&w2c_memory), (u64)(w2c_i0), w2c_f1);
  w2c_i0 = 4u;
  w2c_f1 = 20;
  f32_store((&w2c_memory), (u64)(w2c_i0), w2c_f1);
  FUNC_EPILOGUE;
}

static void w2c_loop(void) {
  u32 w2c_l0 = 0, w2c_l1 = 0, w2c_l2 = 0, w2c_l3 = 0, w2c_l4 = 0, w2c_l5 = 0, w2c_l6 = 0, w2c_l7 = 0, 
      w2c_l8 = 0, w2c_l9 = 0, w2c_l11 = 0, w2c_l12 = 0, w2c_l13 = 0, w2c_l14 = 0;
  f32 w2c_l10 = 0, w2c_l15 = 0;
  FUNC_PROLOGUE;
  u32 w2c_i0, w2c_i1, w2c_i2, w2c_i3, w2c_i4;
  f32 w2c_f0, w2c_f1, w2c_f2, w2c_f3, w2c_f4;
  w2c_i0 = 16u;
  w2c_i0 = i32_load((&w2c_memory), (u64)(w2c_i0));
  w2c_i1 = 4294967196u;
  w2c_i0 = (u32)((s32)w2c_i0 > (s32)w2c_i1);
  w2c_l0 = w2c_i0;
  w2c_i0 = 20u;
  w2c_f0 = f32_load((&w2c_memory), (u64)(w2c_i0));
  w2c_f1 = 0;
  w2c_i0 = w2c_f0 != w2c_f1;
  w2c_l1 = w2c_i0;
  w2c_i0 = w2c_l0;
  if (w2c_i0) {
    w2c_i0 = w2c_l1;
    w2c_l2 = w2c_i0;
  } else {
    w2c_i0 = 0u;
    w2c_l2 = w2c_i0;
  }
  w2c_i0 = w2c_l2;
  if (w2c_i0) {
    w2c_i0 = 8u;
    w2c_i0 = i32_load((&w2c_memory), (u64)(w2c_i0));
    w2c_i1 = 4294967196u;
    w2c_i0 = (u32)((s32)w2c_i0 > (s32)w2c_i1);
    w2c_l3 = w2c_i0;
    w2c_i0 = 12u;
    w2c_f0 = f32_load((&w2c_memory), (u64)(w2c_i0));
    w2c_f1 = 0;
    w2c_i0 = w2c_f0 != w2c_f1;
    w2c_l4 = w2c_i0;
    w2c_i0 = w2c_l3;
    if (w2c_i0) {
      w2c_i0 = w2c_l4;
      w2c_l5 = w2c_i0;
    } else {
      w2c_i0 = 0u;
      w2c_l5 = w2c_i0;
    }
    w2c_i0 = w2c_l5;
    if (w2c_i0) {
      w2c_i0 = 50u;
      w2c_i1 = 0u;
      w2c_f1 = f32_load((&w2c_memory), (u64)(w2c_i1));
      w2c_i2 = 40u;
      w2c_i3 = 45u;
      (*Z_jsZ_drawThwompZ_vifii)(w2c_i0, w2c_f1, w2c_i2, w2c_i3);
      w2c_i0 = 85u;
      w2c_i1 = 255u;
      w2c_i2 = 85u;
      (*Z_jsZ_setFillZ_viii)(w2c_i0, w2c_i1, w2c_i2);
      w2c_i0 = 8u;
      w2c_i0 = i32_load((&w2c_memory), (u64)(w2c_i0));
      w2c_i1 = 10u;
      w2c_i0 += w2c_i1;
      w2c_i1 = 0u;
      w2c_i2 = 80u;
      w2c_i3 = 12u;
      w2c_f3 = f32_load((&w2c_memory), (u64)(w2c_i3));
      w2c_f4 = 50;
      w2c_f3 -= w2c_f4;
      (*Z_jsZ_contextFillRectZ_viiif)(w2c_i0, w2c_i1, w2c_i2, w2c_f3);
      w2c_i0 = 17u;
      w2c_i1 = 255u;
      w2c_i2 = 17u;
      (*Z_jsZ_setFillZ_viii)(w2c_i0, w2c_i1, w2c_i2);
      w2c_i0 = 8u;
      w2c_i0 = i32_load((&w2c_memory), (u64)(w2c_i0));
      w2c_i1 = 12u;
      w2c_f1 = f32_load((&w2c_memory), (u64)(w2c_i1));
      w2c_f2 = 50;
      w2c_f1 -= w2c_f2;
      w2c_i2 = 100u;
      w2c_i3 = 50u;
      (*Z_jsZ_contextFillRectZ_vifii)(w2c_i0, w2c_f1, w2c_i2, w2c_i3);
      w2c_i0 = 17u;
      w2c_i1 = 255u;
      w2c_i2 = 17u;
      (*Z_jsZ_setFillZ_viii)(w2c_i0, w2c_i1, w2c_i2);
      w2c_i0 = 8u;
      w2c_i0 = i32_load((&w2c_memory), (u64)(w2c_i0));
      w2c_i1 = 12u;
      w2c_f1 = f32_load((&w2c_memory), (u64)(w2c_i1));
      w2c_f2 = 150;
      w2c_f1 += w2c_f2;
      w2c_i2 = 100u;
      w2c_i3 = 50u;
      (*Z_jsZ_contextFillRectZ_vifii)(w2c_i0, w2c_f1, w2c_i2, w2c_i3);
      w2c_i0 = 85u;
      w2c_i1 = 255u;
      w2c_i2 = 85u;
      (*Z_jsZ_setFillZ_viii)(w2c_i0, w2c_i1, w2c_i2);
      w2c_i0 = 8u;
      w2c_i0 = i32_load((&w2c_memory), (u64)(w2c_i0));
      w2c_i1 = 10u;
      w2c_i0 += w2c_i1;
      w2c_i1 = 12u;
      w2c_f1 = f32_load((&w2c_memory), (u64)(w2c_i1));
      w2c_f2 = 200;
      w2c_f1 += w2c_f2;
      w2c_i2 = 80u;
      w2c_f3 = 500;
      w2c_i4 = 12u;
      w2c_f4 = f32_load((&w2c_memory), (u64)(w2c_i4));
      w2c_f3 -= w2c_f4;
      (*Z_jsZ_contextFillRectZ_vifif)(w2c_i0, w2c_f1, w2c_i2, w2c_f3);
    }
    w2c_i0 = 85u;
    w2c_i1 = 255u;
    w2c_i2 = 85u;
    (*Z_jsZ_setFillZ_viii)(w2c_i0, w2c_i1, w2c_i2);
    w2c_i0 = 16u;
    w2c_i0 = i32_load((&w2c_memory), (u64)(w2c_i0));
    w2c_i1 = 10u;
    w2c_i0 += w2c_i1;
    w2c_i1 = 0u;
    w2c_i2 = 80u;
    w2c_i3 = 20u;
    w2c_f3 = f32_load((&w2c_memory), (u64)(w2c_i3));
    w2c_f4 = 50;
    w2c_f3 -= w2c_f4;
    (*Z_jsZ_contextFillRectZ_viiif)(w2c_i0, w2c_i1, w2c_i2, w2c_f3);
    w2c_i0 = 17u;
    w2c_i1 = 255u;
    w2c_i2 = 17u;
    (*Z_jsZ_setFillZ_viii)(w2c_i0, w2c_i1, w2c_i2);
    w2c_i0 = 16u;
    w2c_i0 = i32_load((&w2c_memory), (u64)(w2c_i0));
    w2c_i1 = 20u;
    w2c_f1 = f32_load((&w2c_memory), (u64)(w2c_i1));
    w2c_f2 = 50;
    w2c_f1 -= w2c_f2;
    w2c_i2 = 100u;
    w2c_i3 = 50u;
    (*Z_jsZ_contextFillRectZ_vifii)(w2c_i0, w2c_f1, w2c_i2, w2c_i3);
    w2c_i0 = 17u;
    w2c_i1 = 255u;
    w2c_i2 = 17u;
    (*Z_jsZ_setFillZ_viii)(w2c_i0, w2c_i1, w2c_i2);
    w2c_i0 = 16u;
    w2c_i0 = i32_load((&w2c_memory), (u64)(w2c_i0));
    w2c_i1 = 20u;
    w2c_f1 = f32_load((&w2c_memory), (u64)(w2c_i1));
    w2c_f2 = 150;
    w2c_f1 += w2c_f2;
    w2c_i2 = 100u;
    w2c_i3 = 50u;
    (*Z_jsZ_contextFillRectZ_vifii)(w2c_i0, w2c_f1, w2c_i2, w2c_i3);
    w2c_i0 = 85u;
    w2c_i1 = 255u;
    w2c_i2 = 85u;
    (*Z_jsZ_setFillZ_viii)(w2c_i0, w2c_i1, w2c_i2);
    w2c_i0 = 16u;
    w2c_i0 = i32_load((&w2c_memory), (u64)(w2c_i0));
    w2c_i1 = 10u;
    w2c_i0 += w2c_i1;
    w2c_i1 = 20u;
    w2c_f1 = f32_load((&w2c_memory), (u64)(w2c_i1));
    w2c_f2 = 200;
    w2c_f1 += w2c_f2;
    w2c_i2 = 80u;
    w2c_f3 = 500;
    w2c_i4 = 20u;
    w2c_f4 = f32_load((&w2c_memory), (u64)(w2c_i4));
    w2c_f3 -= w2c_f4;
    (*Z_jsZ_contextFillRectZ_vifif)(w2c_i0, w2c_f1, w2c_i2, w2c_f3);
  }
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_f1 = f32_load((&w2c_memory), (u64)(w2c_i1));
  w2c_i2 = 4u;
  w2c_f2 = f32_load((&w2c_memory), (u64)(w2c_i2));
  w2c_f1 += w2c_f2;
  f32_store((&w2c_memory), (u64)(w2c_i0), w2c_f1);
  w2c_i0 = 4u;
  w2c_i1 = 4u;
  w2c_f1 = f32_load((&w2c_memory), (u64)(w2c_i1));
  w2c_f2 = 0.5;
  w2c_f1 += w2c_f2;
  f32_store((&w2c_memory), (u64)(w2c_i0), w2c_f1);
  w2c_i0 = 8u;
  w2c_i1 = 8u;
  w2c_i1 = i32_load((&w2c_memory), (u64)(w2c_i1));
  w2c_i2 = 4294967196u;
  w2c_i1 = (u32)((s32)w2c_i1 < (s32)w2c_i2);
  w2c_l6 = w2c_i1;
  w2c_i1 = 12u;
  w2c_f1 = f32_load((&w2c_memory), (u64)(w2c_i1));
  w2c_f2 = 0;
  w2c_i1 = w2c_f1 == w2c_f2;
  w2c_l7 = w2c_i1;
  w2c_i1 = w2c_l6;
  if (w2c_i1) {
    w2c_i1 = w2c_l6;
    w2c_l8 = w2c_i1;
  } else {
    w2c_i1 = w2c_l7;
    if (w2c_i1) {
      w2c_i1 = w2c_l7;
      w2c_l8 = w2c_i1;
    } else {
      w2c_i1 = 0u;
      w2c_l8 = w2c_i1;
    }
  }
  w2c_i1 = w2c_l8;
  if (w2c_i1) {
    w2c_f1 = 0;
    w2c_i2 = 8u;
    w2c_i2 = i32_load((&w2c_memory), (u64)(w2c_i2));
    w2c_l9 = w2c_i2;
    w2c_l10 = w2c_f1;
  } else {
    w2c_i1 = 12u;
    w2c_f1 = f32_load((&w2c_memory), (u64)(w2c_i1));
    w2c_i2 = 8u;
    w2c_i2 = i32_load((&w2c_memory), (u64)(w2c_i2));
    w2c_i3 = 1u;
    w2c_i2 -= w2c_i3;
    w2c_l9 = w2c_i2;
    w2c_l10 = w2c_f1;
  }
  w2c_i1 = w2c_l9;
  i32_store((&w2c_memory), (u64)(w2c_i0), w2c_i1);
  w2c_i0 = 12u;
  w2c_f1 = w2c_l10;
  f32_store((&w2c_memory), (u64)(w2c_i0), w2c_f1);
  w2c_i0 = 16u;
  w2c_i1 = 16u;
  w2c_i1 = i32_load((&w2c_memory), (u64)(w2c_i1));
  w2c_i2 = 4294967196u;
  w2c_i1 = (u32)((s32)w2c_i1 < (s32)w2c_i2);
  w2c_l11 = w2c_i1;
  w2c_i1 = 20u;
  w2c_f1 = f32_load((&w2c_memory), (u64)(w2c_i1));
  w2c_f2 = 0;
  w2c_i1 = w2c_f1 == w2c_f2;
  w2c_l12 = w2c_i1;
  w2c_i1 = w2c_l11;
  if (w2c_i1) {
    w2c_i1 = w2c_l11;
    w2c_l13 = w2c_i1;
  } else {
    w2c_i1 = w2c_l12;
    if (w2c_i1) {
      w2c_i1 = w2c_l12;
      w2c_l13 = w2c_i1;
    } else {
      w2c_i1 = 0u;
      w2c_l13 = w2c_i1;
    }
  }
  w2c_i1 = w2c_l13;
  if (w2c_i1) {
    w2c_f1 = 0;
    w2c_i2 = 16u;
    w2c_i2 = i32_load((&w2c_memory), (u64)(w2c_i2));
    w2c_l14 = w2c_i2;
    w2c_l15 = w2c_f1;
  } else {
    w2c_i1 = 20u;
    w2c_f1 = f32_load((&w2c_memory), (u64)(w2c_i1));
    w2c_i2 = 16u;
    w2c_i2 = i32_load((&w2c_memory), (u64)(w2c_i2));
    w2c_i3 = 1u;
    w2c_i2 -= w2c_i3;
    w2c_l14 = w2c_i2;
    w2c_l15 = w2c_f1;
  }
  w2c_i1 = w2c_l14;
  i32_store((&w2c_memory), (u64)(w2c_i0), w2c_i1);
  w2c_i0 = 20u;
  w2c_f1 = w2c_l15;
  f32_store((&w2c_memory), (u64)(w2c_i0), w2c_f1);
  (*Z_jsZ_nextFrameZ_vv)();
  FUNC_EPILOGUE;
}

static void w2c_test(void) {
  f32 w2c_l0 = 0, w2c_l1 = 0;
  FUNC_PROLOGUE;
  u32 w2c_i0, w2c_i1, w2c_i2, w2c_i3;
  f32 w2c_f0, w2c_f1, w2c_f2, w2c_f3, w2c_f4, w2c_f5;
  w2c_i0 = 0u;
  w2c_i1 = 0u;
  w2c_i2 = 400u;
  w2c_i3 = 700u;
  (*Z_jsZ_contextClearRectZ_viiii)(w2c_i0, w2c_i1, w2c_i2, w2c_i3);
  w2c_i0 = 50u;
  w2c_f1 = 323;
  w2c_i2 = 40u;
  w2c_i3 = 45u;
  (*Z_jsZ_drawThwompZ_vifii)(w2c_i0, w2c_f1, w2c_i2, w2c_i3);
  w2c_f0 = (*Z_jsZ_MathZ2ErandomZ_fv)();
  w2c_l1 = w2c_f0;
  w2c_f0 = w2c_l1;
  w2c_f1 = 550;
  w2c_f0 *= w2c_f1;
  w2c_f1 = 0;
  w2c_i0 = w2c_f0 != w2c_f1;
  if (w2c_i0) {
    w2c_i0 = 85u;
    w2c_i1 = 255u;
    w2c_i2 = 85u;
    (*Z_jsZ_setFillZ_viii)(w2c_i0, w2c_i1, w2c_i2);
    w2c_i0 = 60u;
    w2c_i1 = 0u;
    w2c_i2 = 80u;
    w2c_f3 = w2c_l1;
    w2c_f4 = 550;
    w2c_f3 *= w2c_f4;
    w2c_f4 = 50;
    w2c_f3 -= w2c_f4;
    (*Z_jsZ_contextFillRectZ_viiif)(w2c_i0, w2c_i1, w2c_i2, w2c_f3);
    w2c_i0 = 17u;
    w2c_i1 = 255u;
    w2c_i2 = 17u;
    (*Z_jsZ_setFillZ_viii)(w2c_i0, w2c_i1, w2c_i2);
    w2c_i0 = 50u;
    w2c_f1 = w2c_l1;
    w2c_f2 = 550;
    w2c_f1 *= w2c_f2;
    w2c_f2 = 50;
    w2c_f1 -= w2c_f2;
    w2c_i2 = 100u;
    w2c_i3 = 50u;
    (*Z_jsZ_contextFillRectZ_vifii)(w2c_i0, w2c_f1, w2c_i2, w2c_i3);
    w2c_i0 = 17u;
    w2c_i1 = 255u;
    w2c_i2 = 17u;
    (*Z_jsZ_setFillZ_viii)(w2c_i0, w2c_i1, w2c_i2);
    w2c_i0 = 50u;
    w2c_f1 = w2c_l1;
    w2c_f2 = 550;
    w2c_f1 *= w2c_f2;
    w2c_f2 = 150;
    w2c_f1 += w2c_f2;
    w2c_i2 = 100u;
    w2c_i3 = 50u;
    (*Z_jsZ_contextFillRectZ_vifii)(w2c_i0, w2c_f1, w2c_i2, w2c_i3);
    w2c_i0 = 85u;
    w2c_i1 = 255u;
    w2c_i2 = 85u;
    (*Z_jsZ_setFillZ_viii)(w2c_i0, w2c_i1, w2c_i2);
    w2c_i0 = 60u;
    w2c_f1 = w2c_l1;
    w2c_f2 = 550;
    w2c_f1 *= w2c_f2;
    w2c_f2 = 200;
    w2c_f1 += w2c_f2;
    w2c_i2 = 80u;
    w2c_f3 = 500;
    w2c_f4 = w2c_l1;
    w2c_f5 = 550;
    w2c_f4 *= w2c_f5;
    w2c_f3 -= w2c_f4;
    (*Z_jsZ_contextFillRectZ_vifif)(w2c_i0, w2c_f1, w2c_i2, w2c_f3);
  }
  w2c_f0 = (*Z_jsZ_MathZ2ErandomZ_fv)();
  w2c_l0 = w2c_f0;
  w2c_f0 = w2c_l0;
  w2c_f1 = 550;
  w2c_f0 *= w2c_f1;
  w2c_f1 = 0;
  w2c_i0 = w2c_f0 != w2c_f1;
  if (w2c_i0) {
    w2c_i0 = 85u;
    w2c_i1 = 255u;
    w2c_i2 = 85u;
    (*Z_jsZ_setFillZ_viii)(w2c_i0, w2c_i1, w2c_i2);
    w2c_i0 = 290u;
    w2c_i1 = 0u;
    w2c_i2 = 80u;
    w2c_f3 = w2c_l0;
    w2c_f4 = 550;
    w2c_f3 *= w2c_f4;
    w2c_f4 = 50;
    w2c_f3 -= w2c_f4;
    (*Z_jsZ_contextFillRectZ_viiif)(w2c_i0, w2c_i1, w2c_i2, w2c_f3);
    w2c_i0 = 17u;
    w2c_i1 = 255u;
    w2c_i2 = 17u;
    (*Z_jsZ_setFillZ_viii)(w2c_i0, w2c_i1, w2c_i2);
    w2c_i0 = 280u;
    w2c_f1 = w2c_l0;
    w2c_f2 = 550;
    w2c_f1 *= w2c_f2;
    w2c_f2 = 50;
    w2c_f1 -= w2c_f2;
    w2c_i2 = 100u;
    w2c_i3 = 50u;
    (*Z_jsZ_contextFillRectZ_vifii)(w2c_i0, w2c_f1, w2c_i2, w2c_i3);
    w2c_i0 = 17u;
    w2c_i1 = 255u;
    w2c_i2 = 17u;
    (*Z_jsZ_setFillZ_viii)(w2c_i0, w2c_i1, w2c_i2);
    w2c_i0 = 280u;
    w2c_f1 = w2c_l0;
    w2c_f2 = 550;
    w2c_f1 *= w2c_f2;
    w2c_f2 = 150;
    w2c_f1 += w2c_f2;
    w2c_i2 = 100u;
    w2c_i3 = 50u;
    (*Z_jsZ_contextFillRectZ_vifii)(w2c_i0, w2c_f1, w2c_i2, w2c_i3);
    w2c_i0 = 85u;
    w2c_i1 = 255u;
    w2c_i2 = 85u;
    (*Z_jsZ_setFillZ_viii)(w2c_i0, w2c_i1, w2c_i2);
    w2c_i0 = 290u;
    w2c_f1 = w2c_l0;
    w2c_f2 = 550;
    w2c_f1 *= w2c_f2;
    w2c_f2 = 200;
    w2c_f1 += w2c_f2;
    w2c_i2 = 80u;
    w2c_f3 = 500;
    w2c_f4 = w2c_l0;
    w2c_f5 = 550;
    w2c_f4 *= w2c_f5;
    w2c_f3 -= w2c_f4;
    (*Z_jsZ_contextFillRectZ_vifif)(w2c_i0, w2c_f1, w2c_i2, w2c_f3);
  }
  FUNC_EPILOGUE;
}

static const u8 data_segment_data_0[] = {
  0x00, 0x00, 0x20, 0x41, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
  0x00, 0x00, 0x00, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 
  
};

static void init_memory(void) {
  wasm_rt_allocate_memory((&w2c_memory), 1, 65536);
  LOAD_DATA(w2c_memory, 0u, data_segment_data_0, 24);
}

static void init_table(void) {
  uint32_t offset;
}

/* export: 'draw' */
void (*WASM_RT_ADD_PREFIX(Z_drawZ_vv))(void);
/* export: 'update' */
void (*WASM_RT_ADD_PREFIX(Z_updateZ_vv))(void);
/* export: 'flap' */
void (*WASM_RT_ADD_PREFIX(Z_flapZ_vv))(void);
/* export: 'loop' */
void (*WASM_RT_ADD_PREFIX(Z_loopZ_vv))(void);
/* export: 'test' */
void (*WASM_RT_ADD_PREFIX(Z_testZ_vv))(void);
/* export: 'memory' */
wasm_rt_memory_t (*WASM_RT_ADD_PREFIX(Z_memory));

static void init_exports(void) {
  /* export: 'draw' */
  WASM_RT_ADD_PREFIX(Z_drawZ_vv) = (&w2c_draw);
  /* export: 'update' */
  WASM_RT_ADD_PREFIX(Z_updateZ_vv) = (&w2c_update);
  /* export: 'flap' */
  WASM_RT_ADD_PREFIX(Z_flapZ_vv) = (&w2c_flap);
  /* export: 'loop' */
  WASM_RT_ADD_PREFIX(Z_loopZ_vv) = (&w2c_loop);
  /* export: 'test' */
  WASM_RT_ADD_PREFIX(Z_testZ_vv) = (&w2c_test);
  /* export: 'memory' */
  WASM_RT_ADD_PREFIX(Z_memory) = (&w2c_memory);
}

void WASM_RT_ADD_PREFIX(init)(void) {
  init_func_types();
  init_globals();
  init_memory();
  init_table();
  init_exports();
}
